Repository tianocore/edk2-pytool-library, pull requests merged in 2020-06, with the labels that each got.

#111 Fix flake errors
  BasicDevTests.py
  edk2toollib/uefi/edk2/build_objects/dsc_translator.py
  edk2toollib/uefi/edk2/parsers/base_parser.py
  edk2toollib/uefi/edk2/parsers/dsc_parser.py
  edk2toollib/uefi/edk2/parsers/dsc_parser_test.py
  edk2toollib/uefi/edk2/path_utilities_test.py
  edk2toollib/windows/locate_tools.py
Labels: bug, ready

#107 Fix links in readme
  readme.md
Labels: bug

#103 [Bug] Fix Build report parser enum warning and convert INF path to Edk2 style
  edk2toollib/uefi/edk2/parsers/buildreport_parser.py
Labels: bug, ready

#110 No fail mode for DSC parser
  edk2toollib/uefi/edk2/parsers/dsc_parser.py
  edk2toollib/uefi/edk2/parsers/dsc_parser_test.py
Labels: ready

#108 Reduce parser debugging output
  edk2toollib/uefi/edk2/parsers/base_parser.py
Labels: ready

#113 Support error or warning configuration for Edk2Path object
  edk2toollib/uefi/edk2/path_utilities.py
  edk2toollib/uefi/edk2/path_utilities_test.py
Labels: enhancement

#112 added codecov support
  azure-pipelines/ubuntu-test-pr-ci.yml
  azure-pipelines/windows-test-pr-ci.yml
Labels: enhancement

#114 Relative Includes on DSCs
  edk2toollib/uefi/edk2/parsers/base_parser.py
  edk2toollib/uefi/edk2/parsers/base_parser_test.py
  edk2toollib/uefi/edk2/parsers/dsc_parser.py
  edk2toollib/uefi/edk2/parsers/dsc_parser_test.py
  edk2toollib/uefi/edk2/path_utilities.py
Labels: ready
