Repository tianocore/edk2-pytool-library, pull requests merged in 2021-08, with the labels that each got.

#136 Add RemoveTree function to consolidate
  edk2toollib/utility_functions.py
Labels: enhancement

#137 Fix incorrectly spelled function.
  edk2toollib/uefi/edk2/parsers/base_parser.py
  edk2toollib/uefi/edk2/path_utilities.py
  edk2toollib/uefi/edk2/path_utilities_test.py
Labels: bug

#135 Add a new inf_generator2 module with support for generating multi-node capsules
  .cspell.json
  edk2toollib/windows/capsule/inf_generator2.py
  edk2toollib/windows/capsule/inf_generator2_test.py
Labels: enhancement

#134 Update encoding to use locale based detection when parsing logs
  edk2toollib/utility_functions.py
Labels: bug, enhancement
