Repository tianocore/edk2-pytool-library, pull requests merged in 2023-05, with the labels that each got.

#324 Transition to Ruff [REBASE&FF]
  .githooks/advanced-pre-commit-config.yaml
  .githooks/basic-pre-commit-config.yaml
  .github/workflows/CIRunner.yml
  .gitignore
  .vscode/extensions.json
  .vscode/settings.json
  edk2toollib/uefi/authenticated_variables_structure_support.py
  edk2toollib/uefi/edk2/guid_list.py
  edk2toollib/uefi/edk2/parsers/guid_parser.py
  edk2toollib/utility_functions.py
  pyproject.toml
Labels: enhancement

#313 locate_tools: set comparison invalid due to mismatched case of keys
  edk2toollib/windows/locate_tools.py
Labels: bug

#314 path_utilities.py: update Edk2Path documentation
  edk2toollib/uefi/edk2/path_utilities.py
Labels: documentation

#315 inf_generator: update DefaultDestDir
  edk2toollib/windows/capsule/inf_generator.py
  edk2toollib/windows/capsule/inf_generator2.py
  tests.unit/test_inf_generator.py
  tests.unit/test_inf_generator2.py
Labels: enhancement

#339 updating vscode settings to point to the unit tests
  .vscode/settings.json
Labels: bug

#340 Issue/update readme
  readme.md
Labels: documentation

#320 locate_tools: add detailed warnings for vcvarsall.bat errors
  edk2toollib/windows/locate_tools.py
  tests.unit/test_locate_tools.py
Labels: bug

#347 dependabot.yml: Update frequency of checks
  .github/dependabot.yml
Labels: dependencies
