Repository tianocore/edk2-pytool-library, pull requests merged in 2023-02, with the labels that each got.

#242 Feature/update/uefi multi phase
  edk2toollib/tests/test_uefi_multi_phase.py
  edk2toollib/uefi/uefi_multi_phase.py
Labels: enhancement

#257 utility_functions: Force GetHostInfo() to return MacOs
  edk2toollib/utility_functions.py
Labels: bug

#260 Update dependencies
  requirements.txt
Labels: ready, dependencies

#269 Update vscode settings
  .vscode/settings.json
Labels: enhancement
