Repository tianocore/edk2-pytool-library, pull requests merged in 2023-10, with the labels that each got.

#419 edk2toollib/uefi/edk2/parsers: enhancements
  edk2toollib/uefi/edk2/parsers/base_parser.py
  edk2toollib/uefi/edk2/parsers/dsc_parser.py
  tests.unit/parsers/test_base_parser.py
Labels: bug, enhancement

#424 Update Supported Python versions to 3.10, 3.11, and 3.12
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/workflows/VariableProducer.yml
  docs/contributor/python_release.md
  pyproject.toml
  readme.md
Labels: enhancement

#437 gitignore_parser.py: Multiple Updates
  edk2toollib/gitignore_parser.py
  tests.unit/parsers/test_gitingore_parser.py
Labels: enhancement

#438 Corrected Logger case to logger in error condition
  edk2toollib/uefi/edk2/path_utilities.py
Labels: bug
