Repository tianocore/edk2-pytool-library, pull requests merged in 2024-06, with the labels that each got.

#577 Adding Uefi Variable Support.
  .cspell.json
  edk2toollib/os/__init__.py
  edk2toollib/os/uefivariablesupport.py
  pyproject.toml
Labels: enhancement

#584 Address Linux GetUefiVariable exception.
  edk2toollib/os/uefivariablesupport.py
Labels: bug

#588 readme: Add documentation on publishing a release
  docs/contributor/publishing.md
  readme.md
Labels: documentation
